#!/bin/bash
#2 update libxml to version 2.8

cd ~/pack/automate_files/files
if [ ! -d "libxml2" ]; then
	git clone git://git.gnome.org/libxml2
	cd ~/pack/automate_files/files/libxml2
	./autogen.sh
	./configure --with-python=/usr/include/python3.3m
	sudo make
	sudo make check
	sudo make install
else
	echo already installed
fi
