#!/bin/bash

# VIM configs
# checkout https://github.com/akitaonrails/vimfiles

if [ ! -d ~/.vim ]; then 
	echo cloning vimfiles...
	git clone git://github.com/akitaonrails/vimfiles.git ~/.vim
	cd ~/.vim/bundle
	## embedding zenCoding for Vim
	git clone http://github.com/mattn/emmet-vim.git
fi

	echo updating vimfiles
	cd ~/.vim ; git submodule update --init

if [ ! -f ~/.vimrc ]; then
	echo creating .vimrc
	echo source ~/.vim/vimrc > ~/.vimrc

fi


