#!/bin/bash

# RVM
# http://igorrocha.com.br/instalando-rvm-no-ubuntu-12-04-e-ambientes-ruby-2-0-0-com-rails-4-0-0-beta1-e-ruby-1-9-3-com-rails-3-2-13/

# dependency
sudo apt-get install curl
# GET stable version
\curl -L https://get.rvm.io | bash -s stable
# install
source /etc/profile.d/rvm.sh
# show version
rvm -v
# post intall
type rvm | head -n 1
rvm requirements


rvm install 2.0.0
rvm --default use 2.0.0
rvm gemset create rails4
rvm use 2.0.0@rails4 --default
gem install rails --no-ri --no-rdoc
# rvm --create --rvmrc 2.0.0@rails4


# done
# ? link your bashrc to rvm.sh
# ? install ruby versions with 'rvm list known' and 'rvm install version'
# ? create your gemsets
# ? set defaults like : rvm use <ruby version>@<gemset name> --default
# ? create rvmrc to the projects 

# ? rvm --rvmrc --create “nome da gemset em rvm list gemsets”
# ? remove "warning" in the .rvmrc file
