#!/bin/bash
if [ "$1" != "i386" -a "$1" != "amd64" ]; then
	echo $0 \(i386/amd64\)
	exit 1
fi

echo Installing Sphinx
# dependencies http://packages.ubuntu.com/oneiric/libmysqlclient16
cd ~/pack/automate_files/files

if ! dpkg -s libmysqlclient16 &> /dev/null ; then
	echo installing dependence libmysqlclient16...
	if [ "$1" == "i386" ]; then
        #wget http://security.ubuntu.com/ubuntu/pool/main/m/mysql-5.1/libmysqlclient16_5.1.66-0ubuntu0.11.10.2_i386.deb
		dpkg -i libmysqlclient16_5.1.66-0ubuntu0.11.10.2_i386.deb
	elif [ "$1" == "amd64" ]; then
        #wget http://security.ubuntu.com/ubuntu/pool/main/m/mysql-5.1/libmysqlclient16_5.1.66-0ubuntu0.11.10.2_amd64.deb
		dpkg -i libmysqlclient16_5.1.66-0ubuntu0.11.10.2_amd64.deb
	fi
	echo ok.
else
	echo dependence libmysqlclient16 already installed!
fi

if ! dpkg -s sphinxsearch &> /dev/null ; then
	echo installing sphinxsearch...
	if [ "$1" == "i386" ]; then
        wget http://sphinxsearch.com/files/sphinxsearch_2.0.8-release-0ubuntu11~precise1_i386.deb
		dpkg -i sphinxsearch_2.0.8-release-0ubuntu11~precise1_i386.deb

	elif [ "$1" == "amd64" ]; then
        wget http://sphinxsearch.com/files/sphinxsearch_2.0.8-release-0ubuntu11~precise1_amd64.deb
		dpkg -i sphinxsearch_2.0.8-release-0ubuntu11~precise1_amd64.deb
	fi
	echo ok.
else
	echo sphinxsearch already installed!
fi

echo done.
echo
