#!/bin/bash
str1="deb http://download.webmin.com/download/repository sarge contrib"
file1="/etc/apt/sources.list"

echo Loading repositories for webmin

if ! grep -Fxq "$str1" "$file1" 
then
	echo doing...
	cat >> /etc/apt/sources.list <<-EOF
	deb http://download.webmin.com/download/repository sarge contrib
	deb http://webmin.mirror.somersettechsolutions.co.uk/repository sarge contrib
	EOF
	echo done.
else
	echo already!
fi
echo
